# Generated by Django 4.2.5 on 2023-10-11 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_full_name', models.CharField(max_length=200)),
                ('customer_phone_number', models.CharField(max_length=200)),
                ('customer_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('no_of_employees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_full_name', models.CharField(max_length=200)),
                ('employee_contact_number', models.CharField(max_length=200)),
                ('employee_address', models.CharField(max_length=200)),
                ('employee_PAN', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.department')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.departmentgroup')),
            ],
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_category_name', models.CharField(max_length=200)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='TaskCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.employee')),
                ('task_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.taskcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_amount', models.FloatField()),
                ('paid_amount', models.FloatField()),
                ('due_amount', models.FloatField()),
                ('bill_file', models.FileField(upload_to='')),
                ('invoice_date', models.DateField()),
                ('task_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.taskcode')),
            ],
        ),
    ]
