# Generated by Django 4.2.5 on 2023-10-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeassociation',
            old_name='staff',
            new_name='employee',
        ),
    ]
