# Generated by Django 4.2.5 on 2023-10-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bill_file',
            field=models.FileField(upload_to='bills/'),
        ),
    ]
