# Generated by Django 4.2.5 on 2023-10-11 08:44

from django.db import migrations, models
import my_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_invoice_bill_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bill_file',
            field=models.FileField(upload_to='bills/', validators=[my_app.models.validate_file_extension]),
        ),
    ]
