# Generated by Django 4.2.5 on 2023-10-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_invoice_task_category'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
    ]
