# Generated by Django 4.2.5 on 2023-10-14 09:50

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_remove_employee_pan_remove_employee_address_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
