# Generated by Django 4.2.5 on 2023-10-15 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_remove_employeeassociation_pan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='employee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
